apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-nginx-chart.fullname" . }}-ingress
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "my-nginx-chart.fullname" . }}-service
                port:
                  number: 80
