apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-nginx-chart.fullname" . }}-service
spec:
  selector:
    app: {{ include "my-nginx-chart.fullname" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
